[build-system]
requires = ["setuptools","numpy","scipy","matplotlib"]
build-backend = "setuptools.build_meta"

[project]
name = "empmap"
authors = [{name = "Zeke Piskulich", email = "piskulichz@gmail.com"}]
dynamic = ["version", "description"]